### ISSUE TITLE
Data corruption after restart

### ISSUE THREAD

**Issue by aemerick** [enzo-project/enzo-e#5] opened 2019-02-27 17:13 UTC
It appears that data dumps generated after a checkpoint restart are corrupted in some fashion. Or at least corrupted in some fashion that yt is unable to open the output. I was able to re-create this problem with the enzo-e master branch using the HelloWorld.in example (input pasted here [here](https://pastebin.com/WYt29iia)). 

In some cases non-utf8 characters popped up in the resulting .parameter and .libconfig files, but there seems to be other issues with the data output itself that I am not sure about. For the input example above, [here](https://pastebin.com/kB4suTLQ) is the yt error output when trying to interact with the data set (yt.load returns without error).

Below are the commands I used to run and then restart the HelloWorld example:

`./charmrun +p2 ./enzo-e HelloWorld.in`

and 

`./charmrun +p2 ./enzo-e +restart checkpoint-0000`

**Comment by aemerick** [comment] 2019-02-27 17:14
There is also a possibility that I'm doing something wrong and there is an issue with how I'm generating the checkpoint files in the first place.....

**Comment by jobordner** [comment] 2019-02-28 19:42
I've confirmed two problems associated with HDF5 data dumps after a restart:

   1. The `.libconfig` file (and `.parameters` file) has a corrupted directory name:
```
       <          dir = [ "HELLO_WORLD_%04d", "count" ];
       ---
       >          dir = [ "HELLO_WORLD_%04d!", "count" ];
```
   2. No `enzo_*` HDF5 attributes (attributes associated with `EnzoBlock` as opposed to `Block`) are saved.
```
       < ATTRIBUTE "enzo_CellWidth" {
       <    DATATYPE  H5T_IEEE_F32LE
       <    DATASPACE  SIMPLE { ( 3 ) / ( 3 ) }
       <    DATA {
       <    (0): 0.003125, 0.003125, 0.5
       <    }
       < } 
       ---
       > ATTRIBUTE "enzo_CellWidth" {
       >    DATATYPE  H5T_STD_I32LE
       >    DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
       >    DATA {
       >    (0): 0
       >    }
       > }
```

**Comment by aemerick** [comment] 2019-04-30 12:59
@jobordner Any updates on the source of this issue? I'm happy to poke around and try and fix it if you can point me to where you think the problem may lie. I'm not exactly sure where some of this info is being read / written during and after the restart.

**Comment by mabruzzo** [comment] 2020-05-20 16:24
Previously when I had replicated this problem, I had an idea for a possible source of the random random characters that gets inserted into the copy of the parameter files that enzo-e generates. It's been a while since I did this, but I want to document this before I completely forget.

I noticed that the random characters are only inserted at the end of arbitrary user-provided arguments of string-type and always before the closing quote (this is perfectly illustrated by the example James provided ``"HELLO_WORLD_%04d"`` became ``"HELLO_WORLD_%04d!"``).

I suspect that the seemingly random character could have something to do with the Null character. In looking at some of the parsing code, I recall seeing some conversions between c-style strings and ``std::string`` and the latter type is not Null character terminated.

This is mostly just speculation but might be worth exploring.

**Closed** 2021-02-11 20:00 UTC
